# 📝 Unit 13.9: Advanced Correlated Dataset (සියලු සම්බන්ධතා සහිතව)

In [52]:
import pandas as pd
import numpy as np

In [53]:
# 1. මූලික සැකසුම්
num_rows = 5000
np.random.seed(42)

# 2. ස්වායත්ත දත්ත (Independent Variables)
age = np.random.randint(18, 65, size=num_rows)
gender = np.random.choice(['male', 'female'], size=num_rows)
workout_min = np.random.randint(10, 150, size=num_rows).astype(float)


In [54]:
# 3. සම්බන්ධතාවයන් ගොඩනැගීම (Building the Web of Correlations)

# Daily_Steps: Workout_Min මත රඳා පවතී
daily_steps = (workout_min * 85) + np.random.normal(1000, 500,size=num_rows)
daily_steps

array([ 8232.97998499,  4856.33704366, 12154.44216659, ...,
        6177.39884669, 12432.04799453,  4258.67996006], shape=(5000,))

In [55]:
# Calories_Burned: Steps සහ Workout දෙකම මත රඳා පවතී

calories_burned = (daily_steps * 0.04 ) + (workout_min * 4) + np.random.normal(50,20,size=num_rows)
calories_burned

array([ 693.83218228,  436.96707849, 1092.73921735, ...,  535.27589625,
       1105.61413569,  315.94405465], shape=(5000,))

In [56]:
# Water_Intake: Steps වැඩි වන විට සිරුරට වැඩිපුර ජලය අවශ්‍ය වේ
water_intake = (daily_steps * 0.0002) + (workout_min * 0.01) + np.random.normal(1,0.5,size=num_rows)
water_intake

array([3.54139703, 2.57187389, 5.268708  , ..., 3.05950585, 4.91766769,
       3.04336911], shape=(5000,))

In [57]:
# Protein_Intake: Workout වැඩි වන විට පටක අලුත්වැඩියාවට ප්‍රෝටීන් අවශ්‍ය වේ
protein_intake = (workout_min * 0.5) + (age * 0.2) + np.random.normal(20,5 ,size=num_rows)
protein_intake

array([ 77.95999764,  51.91787634, 103.35977471, ...,  55.23329516,
        94.13859443,  47.13280035], shape=(5000,))

In [58]:
# Sleep_Hrs: මධ්‍යස්ථ ව්‍යායාම නින්ද වැඩි කරන අතර අධික ව්‍යායාම නින්ද අඩු කළ හැක (ධන සම්බන්ධයක් ගමු)

sleep_hrs = (daily_steps * 0.0001) + np.random.normal(6.5,0.8,size=num_rows)
sleep_hrs

array([6.3919965 , 6.41164141, 8.73195823, ..., 7.52205407, 6.96249636,
       7.47234855], shape=(5000,))

In [59]:
# 4. දත්ත පිරිසිදු කිරීම (සීමාවන් පවත්වා ගැනීම)
daily_steps = np.clip(daily_steps, 500, 20000).round(0)
calories_burned = np.clip(calories_burned, 100, 1500).round(0)
water_intake = np.clip(water_intake, 1.0, 6.0).round(1)
protein_intake = np.clip(protein_intake, 20, 150).round(0)
sleep_hrs = np.clip(sleep_hrs, 4, 10).round(1)

In [60]:
data = {
    'User_ID': [f'U{i:04d}' for i in range(1, num_rows + 1)],
    'Age': age,
    'Gender': gender,
    'Daily_Steps': daily_steps,
    'Workout_Min': workout_min,
    'Calories_Burned': calories_burned,
    'Sleep_Hrs': sleep_hrs,
    'Protein_Intake': protein_intake,
    'Water_Intake': water_intake
}


In [61]:
df_aura_final = pd.DataFrame(data)


In [62]:
# 3. හිතාමතාම NaN values ඇතුළත් කිරීම (5% missing values)
for col in ['Daily_Steps', 'Workout_Min', 'Calories_Burned', 'Sleep_Hrs','Protein_Intake', 'Water_Intake']:
    mask = np.random.random(num_rows) < 0.05
    df_aura_final.loc[mask, col] = np.nan

df_aura_final.tail()

User_ID  Age  Gender  Daily_Steps  Workout_Min  Calories_Burned  \
4995   U4996   33  female          NaN         33.0            392.0   
4996   U4997   22    male       4860.0         45.0              NaN   
4997   U4998   38    male       6177.0          NaN            535.0   
4998   U4999   27  female      12432.0        139.0           1106.0   
4999   U5000   36  female       4259.0         37.0            316.0   

      Sleep_Hrs  Protein_Intake  Water_Intake  
4995        6.5            39.0           2.5  
4996        6.9            43.0           2.5  
4997        7.5            55.0           3.1  
4998        7.0            94.0           4.9  
4999        7.5             NaN           3.0

In [63]:
# 6. Save කිරීම (Root data folder එකට)
df_aura_final.to_csv('../data/aura_fitness_final.csv', index=False)
print("Successful! The 'aura_fitness_final.csv' file with all connections was created. 🚀")

Successful! The 'aura_fitness_final.csv' file with all connections was created. 🚀


## ⚠️ Common Errors (පරෙස්සම් වෙන්න!)
- 1.Circular Dependency: එක Column එකක් තව එකක් මත රඳා පවතිද්දී, ඒක ආපහු මුල් එක මතම රඳා පවතින ලෙස කේතය ලිව්වොත් එය විශාල අවුලක් විය හැක. හැමවිටම එක දිශාවකට (Linear flow) සම්බන්ධතා තබන්න.

- 2.Unrealistic Values: සීමාවන් (Clips) නොදැම්මොත්, කෙනෙක් දවසකට වතුර ලීටර් 50ක් බොනවා වැනි අසාමාන්‍ය දත්ත නිර්මාණය විය හැක.

## 💼 Interview Question (Advanced)
- ප්‍රශ්නය: "දත්ත විද්‍යාවේදී 'Domain Knowledge' (විෂය පථය පිළිබඳ දැනුම) වැදගත් වන්නේ ඇයි?"
- පිළිතුර: දත්ත නිර්මාණය කිරීමේදී හෝ විශ්ලේෂණය කිරීමේදී සැබෑ ලෝකයේ සිදුවන දේ (උදා: ව්‍යායාම වැඩි වන විට කැලරි දහනය වැඩි වීම) පිළිබඳ අවබෝධයක් තිබීම අත්‍යවශ්‍යයි. මෙම දැනුම නොමැතිව කරන විශ්ලේෂණයන් වැරදි නිගමනවලට මඟ පෑදිය හැක.